Update terraform-dev.yml

diff --git a/.github/workflows/terraform-dev.yml b/.github/workflows/terraform-dev.yml
--- a/.github/workflows/terraform-dev.yml
+++ b/.github/workflows/terraform-dev.yml
@@ -49,9 +49,9 @@ jobs:
           export TF_WORKSPACE="dev"
           terraform plan -input=false
           
-    - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+    #- name: Terraform Plan Status
+    #  if: steps.plan.outcome == 'failure'
+    #  run: exit 1
       
       # On push to "main", build or change infrastructure according to Terraform configuration files
       # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
